### ISSUE TITLE
Question about the kipoi-veff2 requirement for running the annotation pipeline

### ISSUE THREAD

**Issue by pichuan** [PMBio/deeprvat#112]
Hi, I'm following:
https://deeprvat.readthedocs.io/en/latest/annotations.html#requirements

One of the requirements was [kipoi-veff2](https://github.com/kipoi/kipoi-veff2).

When looking through their GitHub, I realize they only support up to Python 3.7. 
It seems like Python 3.7 is no longer support. So it doesn't seem like I can install kipoi-veff2.
Given that this is a requirement for running deeprvat annotations pipeline, can you advise how I can install kipoi-veff2 so that I can meet the requirements here?
If it is possible to skip this requirement, please also let me know.

Thank you!

**Comment by Marcel-Mueck** [comment]
Hello Pi Chuan, 
I updated the docs of the annotation pipeline. 
The installation of the packages is described in the [preconfiguration](https://deeprvat.readthedocs.io/en/latest/annotations.html#preconfiguration) part of the documentation. Specifically, the annotation pipeline is run with multiple conda environmets, so you would have to install the [kipoi-veff2 environment](https://github.com/kipoi/kipoi-veff2/blob/main/environment.minimal.linux.yml) as well as the [deeprvat annotations environment](https://github.com/PMBio/deeprvat/blob/main/deeprvat_annotations.yml).

**Comment by pichuan** [comment]
Thanks @Marcel-Mueck . I'm still having some issue with it. Here is what I do when I install. Can you take a look and see what I'm missing?

# Worklog

I get a machine  with Ubuntu 22.04.

Here is the specific command I used:

`gcloud compute instances create "${USER}-gpu"   --scopes "compute-rw,storage-full,cloud-platform"   --maintenance-policy "TERMINATE"   --accelerator=type=nvidia-tesla-p100,count=1   --image-family "ubuntu-2204-lts"   --image-project "ubuntu-os-cloud"   --machine-type "n1-standard-16"   --boot-disk-size "2000"   --zone "us-west1-b"`

(I got more disk space because some of the requirements seem to have large files. If that's unnecessary please let me know)

Given that my main issue reported here was with `kipoi-veff2`, I'll report my steps and issues on that:

Once ssh into my machine, I first installed mamba:

```bash
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
bash Miniforge3-Linux-x86_64.sh
```

Then, I logged out and relogged in.

Then, following https://deeprvat.readthedocs.io/en/latest/annotations.html#preconfiguration, I ran:

```
git clone https://github.com/PMBio/deeprvat.git
```

And because the instruction said "Clone the repositories mentioned in requirements into repo_dir", I did:

```
git clone https://github.com/kipoi/kipoi-veff2.git
git clone https://github.com/Ensembl/ensembl-vep.git
git clone https://github.com/HealthML/faatpipe.git
mkdir repo_dir
mv kipoi-veff2 repo_dir/
mv ensembl-vep repo_dir/
mv faatpipe repo_dir/
```

At this point, I have:

```
$ ls repo_dir/
ensembl-vep  faatpipe  kipoi-veff2
```

Then I ran:

```
mamba env create -f deeprvat/deeprvat_annotations.yml
mamba activate deeprvat_annotations
pip install -e deeprvat
```

This worked. I got:

```
Obtaining file:///home/pichuan/deeprvat
  Preparing metadata (setup.py) ... done
Installing collected packages: deeprvat
  Running setup.py develop for deeprvat
Successfully installed deeprvat-0.1.0
```

Then, I ran:

```
mamba env create -f repo_dir/kipoi-veff2/environment.minimal.linux.yml
```

This is when I encountered some issue. Because I'm not sure exactly what error is relevant, so I'll paste the whole log below. 

If you see what I'm missing in my steps above that resulted in this, please let me know. Thank you!


```
(deeprvat_annotations) pichuan@pichuan-gpu:~$ mamba env create -f repo_dir/kipoi-veff2/environment.minimal.linux.yml
Channels:
 - pytorch
 - bioconda
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 24.3.0
    latest version: 24.7.1

Please update conda by running

    $ conda update -n base -c conda-forge conda



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: - Ran pip subprocess with arguments:
['/home/pichuan/miniforge3/envs/kipoi-veff2/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/pichuan/repo_dir/kipoi-veff2/condaenv.3hptlvcg.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting gffutils==0.10.1
  Downloading gffutils-0.10.1.tar.gz (1.5 MB)  
Collecting pytest
  Downloading pytest-7.4.4-py3-none-any.whl (325 kB)
Collecting h5py==2.10.0
  Downloading h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9 MB)
Collecting keras==2.2.4
  Downloading Keras-2.2.4-py2.py3-none-any.whl (312 kB)
Collecting mmsplice==2.2.0
  Downloading mmsplice-2.2.0.tar.gz (62.4 MB)  
Collecting pysam==0.16.0.1
  Downloading pysam-0.16.0.1-cp37-cp37m-manylinux1_x86_64.whl (9.9 MB)
Collecting scikit-learn==0.19.2
  Downloading scikit_learn-0.19.2-cp37-cp37m-manylinux1_x86_64.whl (4.9 MB)
Collecting scipy==1.5.4
  Downloading scipy-1.5.4-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
Collecting kipoi
  Downloading kipoi-0.8.6-py3-none-any.whl (102 kB)
Collecting kipoi-conda
  Downloading kipoi_conda-0.3.1-py3-none-any.whl (8.7 kB)
Collecting kipoi-utils
  Downloading kipoi_utils-0.7.7-py3-none-any.whl (30 kB)
Collecting sorted-nearest==0.0.33
  Downloading sorted_nearest-0.0.33.tar.gz (1.2 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started 
  Getting requirements to build wheel: finished with status 'error'

Pip subprocess error:
  ERROR: Command errored out with exit status 1:
   command: /home/pichuan/miniforge3/envs/kipoi-veff2/bin/python /home/pichuan/miniforge3/envs/kipoi-veff2/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpdnpl4ezn
       cwd: /tmp/pip-install-zeomktjz/sorted-nearest
  Complete output (173 lines):

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  @cython.boundscheck(False)
  @cython.wraparound(False)
  @cython.initializedcheck(False)
  cpdef annotate_clusters64(const long [::1] starts, const long [::1] ends, int slack):

      cpdef int min_start = starts[0]
            ^
  ------------------------------------------------------------

  sorted_nearest/src/annotate_clusters.pyx:23:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  @cython.wraparound(False)
  @cython.initializedcheck(False)
  cpdef annotate_clusters64(const long [::1] starts, const long [::1] ends, int slack):

      cpdef int min_start = starts[0]
      cpdef int max_end = ends[0]
            ^
  ------------------------------------------------------------

  sorted_nearest/src/annotate_clusters.pyx:24:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  @cython.initializedcheck(False)
  cpdef annotate_clusters64(const long [::1] starts, const long [::1] ends, int slack):

      cpdef int min_start = starts[0]
      cpdef int max_end = ends[0]
      cpdef int i = 0
            ^
  ------------------------------------------------------------

  sorted_nearest/src/annotate_clusters.pyx:25:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  cpdef annotate_clusters64(const long [::1] starts, const long [::1] ends, int slack):

      cpdef int min_start = starts[0]
      cpdef int max_end = ends[0]
      cpdef int i = 0
      cpdef int n_clusters = 1
            ^
  ------------------------------------------------------------
  sorted_nearest/src/annotate_clusters.pyx:26:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

  Error compiling Cython file:
  ------------------------------------------------------------
  ...

      cpdef int min_start = starts[0]
      cpdef int max_end = ends[0]
      cpdef int i = 0
      cpdef int n_clusters = 1
      cpdef int length = len(starts)
            ^
  ------------------------------------------------------------

  sorted_nearest/src/annotate_clusters.pyx:27:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  @cython.boundscheck(False)
  @cython.wraparound(False)
  @cython.initializedcheck(False)
  cpdef annotate_clusters32(const int32_t [::1] starts, const int32_t [::1] ends, int slack):

      cpdef int min_start = starts[0]
            ^
  ------------------------------------------------------------

  sorted_nearest/src/annotate_clusters.pyx:55:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  @cython.wraparound(False)
  @cython.initializedcheck(False)
  cpdef annotate_clusters32(const int32_t [::1] starts, const int32_t [::1] ends, int slack):

      cpdef int min_start = starts[0]
      cpdef int max_end = ends[0]
            ^
  ------------------------------------------------------------

  sorted_nearest/src/annotate_clusters.pyx:56:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  @cython.initializedcheck(False)
  cpdef annotate_clusters32(const int32_t [::1] starts, const int32_t [::1] ends, int slack):

      cpdef int min_start = starts[0]
      cpdef int max_end = ends[0]
      cpdef int i = 0
            ^
  ------------------------------------------------------------

  sorted_nearest/src/annotate_clusters.pyx:57:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  cpdef annotate_clusters32(const int32_t [::1] starts, const int32_t [::1] ends, int slack):

      cpdef int min_start = starts[0]
      cpdef int max_end = ends[0]
      cpdef int i = 0
      cpdef int n_clusters = 1
            ^
  ------------------------------------------------------------

  sorted_nearest/src/annotate_clusters.pyx:58:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.

  Error compiling Cython file:
  ------------------------------------------------------------
  ...

      cpdef int min_start = starts[0]
      cpdef int max_end = ends[0]
      cpdef int i = 0
      cpdef int n_clusters = 1
      cpdef int length = len(starts)
            ^
  ------------------------------------------------------------

  sorted_nearest/src/annotate_clusters.pyx:59:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
  Compiling sorted_nearest/src/sorted_nearest.pyx because it changed.
  Compiling sorted_nearest/src/max_disjoint_intervals.pyx because it changed.
  Compiling sorted_nearest/src/k_nearest.pyx because it changed.
  Compiling sorted_nearest/src/k_nearest_ties.pyx because it changed.
  Compiling sorted_nearest/src/clusters.pyx because it changed.
  Compiling sorted_nearest/src/annotate_clusters.pyx because it changed.
  Compiling sorted_nearest/src/cluster_by.pyx because it changed.
  Compiling sorted_nearest/src/merge_by.pyx because it changed.
  Compiling sorted_nearest/src/introns.pyx because it changed.
  Compiling sorted_nearest/src/windows.pyx because it changed.
  Compiling sorted_nearest/src/tiles.pyx because it changed.
  [ 1/11] Cythonizing sorted_nearest/src/annotate_clusters.pyx
  Traceback (most recent call last):
    File "/home/pichuan/miniforge3/envs/kipoi-veff2/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/pichuan/miniforge3/envs/kipoi-veff2/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/pichuan/miniforge3/envs/kipoi-veff2/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-qs8y44v3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-qs8y44v3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-qs8y44v3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-qs8y44v3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 79, in <module>
    File "/tmp/pip-build-env-qs8y44v3/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
      cythonize_one(*args)
    File "/tmp/pip-build-env-qs8y44v3/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
      raise CompileError(None, pyx_file)
  Cython.Compiler.Errors.CompileError: sorted_nearest/src/annotate_clusters.pyx
  ----------------------------------------
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pichuan/miniforge3/envs/kipoi-veff2/bin/python /home/pichuan/miniforge3/envs/kipoi-veff2/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpdnpl4ezn Check the logs for full command output.
                                                                                                                                                                               failed

CondaEnvException: Pip failed
```

**Comment by Marcel-Mueck** [comment]
Dear Pi Chuan,
Thank you for the update. 
Are you able to install the kipoi-veff2 environment without the `sorted-nearest ` package? I.e. after commenting out the `sorted-earest` line from the pip dependencies of the `environment.minimal.linux.yml` file? If yes, are you able to activate the environment and run `pip install sorted-nearest`?
This would help me to identify what the problem is. 
Thank you and regards,
 Marcel Mück

**Comment by pichuan** [comment]
Thanks!

I tried two more things:

## (1) Modify sorted-nearest version to 0.0.35 in repo_dir/kipoi-veff2/environment.minimal.linux.yml. --> didn't work due to Python version.

Here is the first thing I tried:

Before installing kipoi-veff2,
I did this first:
```
sed -i -e "s/sorted-nearest==0.0.33/sorted-nearest==0.0.35/g" repo_dir/kipoi-veff2/environment.minimal.linux.yml
```
Then I ran:
```
mamba env create -f repo_dir/kipoi-veff2/environment.minimal.linux.yml
```

That didn't work, because:

```
Pip subprocess error:
ERROR: Package 'setuptools' requires a different Python: 3.7.12 not in '>=3.8'
```

## (2) Remove sorted-nearest from repo_dir/kipoi-veff2/environment.minimal.linux.yml first

Instead of changing the version of `sorted-nearest`, I remove it first:

```
grep -v sorted-nearest repo_dir/kipoi-veff2/environment.minimal.linux.yml > tmpfile && mv tmpfile repo_dir/kipoi-veff2/environment.minimal.linux.yml
```

And then:

```
mamba env create -f repo_dir/kipoi-veff2/environment.minimal.linux.yml
```

However, that still seems to give me the same Python version issue. Here is the full log:

```
(deeprvat_annotations) pichuan@pichuan-gpu2:~$ mamba env create -f repo_dir/kipoi-veff2/environment.minimal.linux.yml
Channels:
 - pytorch
 - bioconda
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 24.3.0
    latest version: 24.7.1

Please update conda by running

    $ conda update -n base -c conda-forge conda



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/home/pichuan/miniforge3/envs/kipoi-veff2/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/pichuan/repo_dir/kipoi-veff2/condaenv.tj4bxo_a.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting gffutils==0.10.1
  Downloading gffutils-0.10.1.tar.gz (1.5 MB)  
Collecting pytest
  Downloading pytest-7.4.4-py3-none-any.whl (325 kB)
Collecting h5py==2.10.0
  Downloading h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9 MB)
Collecting keras==2.2.4
  Downloading Keras-2.2.4-py2.py3-none-any.whl (312 kB)
Collecting mmsplice==2.2.0
  Downloading mmsplice-2.2.0.tar.gz (62.4 MB)  
Collecting pysam==0.16.0.1
  Downloading pysam-0.16.0.1-cp37-cp37m-manylinux1_x86_64.whl (9.9 MB)
Collecting scikit-learn==0.19.2
  Downloading scikit_learn-0.19.2-cp37-cp37m-manylinux1_x86_64.whl (4.9 MB)
Collecting scipy==1.5.4
  Downloading scipy-1.5.4-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
Collecting kipoi
  Downloading kipoi-0.8.6-py3-none-any.whl (102 kB)
Collecting kipoi-conda
  Downloading kipoi_conda-0.3.1-py3-none-any.whl (8.7 kB)
Collecting kipoi-utils
  Downloading kipoi_utils-0.7.7-py3-none-any.whl (30 kB)
Collecting kipoiseq
  Downloading kipoiseq-0.7.1-py3-none-any.whl (44 kB)
Collecting typing-extensions==4.1.1
  Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting attrs==21.4.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting pyfaidx>=0.5.5.2
  Downloading pyfaidx-0.8.1.1-py3-none-any.whl (28 kB)
Requirement already satisfied, skipping upgrade: six>=1.12.0 in /home/pichuan/miniforge3/envs/kipoi-veff2/lib/python3.7/site-packages (from gffutils==0.10.1->-r /home/pichuan/repo_dir/kipoi-veff2/condaenv.tj4bxo_a.requirements.txt (line 1)) (1.16.0)
Collecting argh>=0.26.2
  Downloading argh-0.27.2-py2.py3-none-any.whl (43 kB)
Collecting argcomplete>=1.9.4
  Downloading argcomplete-3.1.2-py3-none-any.whl (41 kB)
Collecting simplejson
  Downloading simplejson-3.19.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (126 kB)
Collecting packaging
  Downloading packaging-24.0-py3-none-any.whl (53 kB)
Requirement already satisfied, skipping upgrade: importlib-metadata>=0.12; python_version < "3.8" in /home/pichuan/miniforge3/envs/kipoi-veff2/lib/python3.7/site-packages (from pytest->-r /home/pichuan/repo_dir/kipoi-veff2/condaenv.tj4bxo_a.requirements.txt (line 2)) (4.11.4)
Collecting exceptiongroup>=1.0.0rc8; python_version < "3.11"
  Downloading exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
Collecting iniconfig
  Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting pluggy<2.0,>=0.12
  Downloading pluggy-1.2.0-py3-none-any.whl (17 kB)
Collecting tomli>=1.0.0; python_version < "3.11"
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Requirement already satisfied, skipping upgrade: numpy>=1.7 in /home/pichuan/miniforge3/envs/kipoi-veff2/lib/python3.7/site-packages (from h5py==2.10.0->-r /home/pichuan/repo_dir/kipoi-veff2/condaenv.tj4bxo_a.requirements.txt (line 3)) (1.18.5)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in /home/pichuan/miniforge3/envs/kipoi-veff2/lib/python3.7/site-packages (from keras==2.2.4->-r /home/pichuan/repo_dir/kipoi-veff2/condaenv.tj4bxo_a.requirements.txt (line 4)) (1.1.2)
Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in /home/pichuan/miniforge3/envs/kipoi-veff2/lib/python3.7/site-packages (from keras==2.2.4->-r /home/pichuan/repo_dir/kipoi-veff2/condaenv.tj4bxo_a.requirements.txt (line 4)) (1.0.8)
Collecting pyyaml
  Downloading PyYAML-6.0.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (670 kB)
Requirement already satisfied, skipping upgrade: setuptools in /home/pichuan/miniforge3/envs/kipoi-veff2/lib/python3.7/site-packages (from mmsplice==2.2.0->-r /home/pichuan/repo_dir/kipoi-veff2/condaenv.tj4bxo_a.requirements.txt (line 5)) (69.0.3)

Pip subprocess error:
ERROR: Package 'setuptools' requires a different Python: 3.7.12 not in '>=3.8'
                                                                                                                                                                                                   failed

CondaEnvException: Pip failed
```

Please let me know what I should try next. Thank you!

**Comment by Marcel-Mueck** [comment]
Dear @pichuan,
I could recreate your error and could fix it after pinning down some more pip dependencies as well as changing the version for the `sorted-nearest` package: 
Here is a yaml file that works for me: 
[working-kipoi-veff2.yml.txt](https://github.com/user-attachments/files/16428658/working-kipoi-veff2.yml.txt).
Note that in this file, for the package `sorted-nearest==0.0.39` the version was changed and `markdown==3.3.6`and `setuptools==62.1.0` were added as pip dependencies.
Please keep me updated on whether this updated file works for you. 
I created an issue in the `kipoi-veff2` repo asking for the `yaml` file to be changed.
Thank you and regards,
Marcel M.

**Comment by pichuan** [comment]
Thanks. 

I was able to do this:

```
wget https://github.com/user-attachments/files/16428658/working-kipoi-veff2.yml.txt
mv working-kipoi-veff2.yml.txt repo_dir/kipoi-veff2/environment.minimal.linux.yml
```

And then:

```
mamba env create -f repo_dir/kipoi-veff2/environment.minimal.linux.yml
```

That worked now! Thanks. I will close this issue and try to follow the remaining steps.
